version: 2
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/buildpack-deps:14.04-curl-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "requirements.txt" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            apt update
            add-apt-repository ppa:ubuntu-toolchain-r/test
            apt-get update
            apt install -y g++-7 libtiff5-dev libgomp1 libfftw3-dev libboost-all-dev libeigen3-dev libyaml-cpp-dev

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            export OMP_NUM_THREADS=4
            export LDFLAGS='-pthread'
            cmake .. -DCMAKE_BUILD_TYPE=Release -Dtests=ON -Dexamples=OFF \
            -Ddompi=ON -Dopenmp=ON -Ddocs=OFF -Dbenchmarks=OFF \
            -DSopt_GIT_REPOSITORY=https://github.com/astro-informatics/sopt.git \
            -DSopt_GIT_TAG=development \
            -DCFitsIO_URL=https://github.com/UCL-RITS/BinaryBlobs-dependencies/raw/master/Astronomy/cfitsio3410.tar.gz \
            -DMPIEXEC:FILEPATH=$(which mpirun) -DMPIEXEC_MAX_NUMPROCS=4

      - run:
          name: run tests
          command: |
            ctest -T test --output-on-failure -V

      - store_artifacts:
          path: test-reports
          destination: test-reports
